export default [
  { name: '对话框', type: 'icon-duihuakuang' },
  { name: '闹钟', type: 'icon-naozhong' },
  { name: '笑脸', type: 'icon-xiaolian' },
  { name: 'ok', type: 'icon-ok' },
  { name: '风车', type: 'icon-fengche' },
  { name: '汗颜', type: 'icon-hanyan' },
  { name: '相机', type: 'icon-xiangji' },
  { name: '礼物', type: 'icon-liwu' },
  { name: '礼花', type: 'icon-lihua' },
  { name: '扭蛋', type: 'icon-niudan' },
  { name: '流星', type: 'icon-liuxing' },
  { name: '风筝', type: 'icon-fengzheng' },
  { name: '蛋糕', type: 'icon-dangao' },
  { name: '泡泡', type: 'icon-paopao' },
  { name: '购物', type: 'icon-gouwu' },
  { name: '饮料', type: 'icon-yinliao' },
  { name: '云彩', type: 'icon-yuncai' },
  { name: '彩铅', type: 'icon-caiqian' },
  { name: '纸飞机', type: 'icon-zhifeiji' },
  { name: '点赞', type: 'icon-dianzan' },
  { name: '煎蛋', type: 'icon-jiandan' },
  { name: '小熊', type: 'icon-xiaoxiong' },
  { name: '花', type: 'icon-hua' },
  { name: '眼睛', type: 'icon-yanjing' },
]
  